// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: addTask.sql

package database

import (
	"context"
)

const addTask = `-- name: AddTask :one
INSERT INTO tasks (type, value,state,creationtime,lastupdatetime)
VALUES (?1, ?2, 'RECEIVED',strftime('%s','now'),strftime('%s','now')) RETURNING id, creationtime
`

type AddTaskParams struct {
	Param1 int64
	Param2 int64
}

type AddTaskRow struct {
	ID           int64
	Creationtime int64
}

func (q *Queries) AddTask(ctx context.Context, arg AddTaskParams) (AddTaskRow, error) {
	row := q.db.QueryRowContext(ctx, addTask, arg.Param1, arg.Param2)
	var i AddTaskRow
	err := row.Scan(&i.ID, &i.Creationtime)
	return i, err
}
