// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: getNumberOfTasks.sql

package database

import (
	"context"
)

const getNumberOfTasks = `-- name: GetNumberOfTasks :one
SELECT COUNT(*)
FROM tasks
WHERE state=?1
`

func (q *Queries) GetNumberOfTasks(ctx context.Context, param1 string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNumberOfTasks, param1)
	var count int64
	err := row.Scan(&count)
	return count, err
}
