// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: updateTask.sql

package database

import (
	"context"
)

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET 
    state=?1, 
    lastupdatetime = strftime('%s','now')
WHERE 
    id=?2
RETURNING id, type, value, state, creationtime, lastupdatetime
`

type UpdateTaskParams struct {
	Param2 string
	Param1 int64
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask, arg.Param2, arg.Param1)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Value,
		&i.State,
		&i.Creationtime,
		&i.Lastupdatetime,
	)
	return i, err
}
