// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: addTask.sql

package database

import (
	"context"
)

const addTask = `-- name: AddTask :one
INSERT INTO tasks (type, value,state,creationtime,lastupdatetime)
VALUES ($1, $2, 'RECEIVED',EXTRACT(EPOCH FROM NOW()),EXTRACT(EPOCH FROM NOW())) RETURNING id, creationtime
`

type AddTaskParams struct {
	Type  int32
	Value int32
}

type AddTaskRow struct {
	ID           int32
	Creationtime int64
}

func (q *Queries) AddTask(ctx context.Context, arg AddTaskParams) (AddTaskRow, error) {
	row := q.db.QueryRowContext(ctx, addTask, arg.Type, arg.Value)
	var i AddTaskRow
	err := row.Scan(&i.ID, &i.Creationtime)
	return i, err
}
