// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type Task struct {
	ID             int64
	Type           int64
	Value          int64
	State          string
	Creationtime   int64
	Lastupdatetime int64
}
