// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: updateTask.sql

package database

import (
	"context"
)

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET 
    state=$2::task_state, 
    lastupdatetime = EXTRACT(EPOCH FROM NOW())
WHERE 
    id=$1
RETURNING id, type, value, state, creationtime, lastupdatetime
`

type UpdateTaskParams struct {
	ID      int32
	Column2 TaskState
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask, arg.ID, arg.Column2)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Value,
		&i.State,
		&i.Creationtime,
		&i.Lastupdatetime,
	)
	return i, err
}
