version: "2"
sql:
    - engine: "sqlite"
      queries: "./database/query/"
      schema: "./database/schema.sql"
      gen:
          go:
              package: "database"
              out: "./database/sqlc"